name: user_repository
description: The Repo that handles users.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_riverpod: ^2.4.10

  #firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # image related packages
  # image_picker: ^1.0.7
  # cached_network_image: ^3.3.1

  # icons
  # cupertino_icons: ^1.0.6
  # font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
